CREATE OR REPLACE PROCEDURE BLHSRVLIB.SP_SE_VAR_PROCESARPAGOS_EXTERIOR (        
  IN INUMIDREFENCIA NUMERIC(12, 0) DEFAULT  0  ,                                
  IN INUMCIFPAGADOR NUMERIC(12, 0) DEFAULT  0  )                                
  LANGUAGE SQL                                                                  
  SPECIFIC BLHSRVLIB.SP_SE_VAR_PROCESARPAGOS_EXTERIOR                           
  NOT DETERMINISTIC                                                             
  MODIFIES SQL DATA                                                             
  CALLED ON NULL INPUT                                                          
  SET OPTION  ALWBLK = *ALLREAD ,                                               
  ALWCPYDTA = *OPTIMIZE ,                                                       
  COMMIT = *CHG ,                                                               
  DBGVIEW = *SOURCE ,                                                           
  DECRESULT = (31, 31, 00) ,                                                    
  DFTRDBCOL = *NONE ,                                                           
  DLYPRP = *NO ,                                                                
  DYNDFTCOL = *NO ,                                                             
  DYNUSRPRF = *OWNER ,                                                          
  RDBCNNMTH = *RUW ,                                                            
  SQLCURRULE = *STD ,                                                           
  SRTSEQ = *HEX                                                                 
    P1 : BEGIN

		--1. Declaramos las variables a utilizar 
--=======================================================================================  
		DECLARE INTTIPORESULTADO INTEGER ;
		DECLARE INTCODIGOERROR INTEGER ;
		DECLARE VARMENSAJERESULTADO VARCHAR ( 1000 ) ;
		DECLARE VARMENSAJE VARCHAR ( 1000 ) ;

		DECLARE DATFECHAACTUAL DATE ;
		DECLARE TIMFECHAACTUAL TIMESTAMP ;	
		DECLARE INTSINREGISTROS INTEGER DEFAULT 0 ;
		
		DECLARE CHRPROSEGUIR CHAR ( 1 ) ;
		DECLARE INTESTADOPROCESO SMALLINT ;
		DECLARE DECTCUSDCOMPRA DECIMAL ( 11 , 6 ) ;
		DECLARE DECTCUSDVENTA DECIMAL ( 11 , 6 ) ;
		DECLARE DECTCUSDOFICIAL DECIMAL ( 11 , 6 ) ;
		DECLARE DECTCEURCOMPRA DECIMAL ( 11 , 6 ) ;
		DECLARE DECTCEURVENTA DECIMAL ( 11 , 6 ) ;
		DECLARE CHRMONEDABASE CHAR ( 3 ) ;

		DECLARE NUMIDUNICOFACTURA NUMERIC ( 12 , 0 ) ;
		DECLARE NUMCTAPAGADOR_ANT NUMERIC ( 16 , 0 ) ;
		DECLARE NUMIDBENEFICIARIO_ANT NUMERIC ( 12 , 0 ) ;
		DECLARE NUMFORMAPAGO_ANT NUMERIC ( 3 , 0 ) ;
		DECLARE CHRMONEDAFACTURA_ANT CHAR ( 3 ) ;
		DECLARE NUMCIFPAGADOR NUMERIC ( 12 , 0 ) ;
		DECLARE NUMCIFBENEFICIARIO NUMERIC ( 12 , 0 ) ;
		DECLARE NUMCUENTABENEFICIARIO NUMERIC ( 16 , 0 ) ;
		DECLARE VARNOMBREBENEFICIARIO VARCHAR ( 200 ) ;
		DECLARE VARCELULARBENEFICIARIO VARCHAR ( 50 ) ;

		DECLARE INTCONTADORFACTOK INTEGER DEFAULT 0 ;
		DECLARE INTTOTALFACT INTEGER DEFAULT 0 ;
		DECLARE DECMONTODEBITO DECIMAL ( 18 , 2 ) ;
		DECLARE DECMONTOCREDITO DECIMAL ( 18 , 2 ) ;
		DECLARE DECMONTODEBITOTEMP DECIMAL ( 18 , 2 ) ;
		DECLARE DECMONTOCREDITOTEMP DECIMAL ( 18 , 2 ) ;

		DECLARE VARDESCRIPCIONDEBITO VARCHAR ( 30 ) ;
		DECLARE VARDESCRIPCIONCREDITO VARCHAR ( 30 ) ;
		DECLARE VARNOMBREPAGADOR VARCHAR ( 35 ) ;
		DECLARE NUMNUMEROSEGURIDAD NUMERIC ( 12 , 0 ) DEFAULT 0 ;

		DECLARE CHRHORA VARCHAR ( 8 ) ;
		DECLARE DECCIF DECIMAL ( 12 , 0 ) DEFAULT 0 ;
		DECLARE CHRESTADO CHAR ( 1 ) ;
		DECLARE NUMSALDODISPONIBLECUENTA NUMERIC ( 18 , 2 ) ;
		DECLARE CHRMONEDACTAPAGADOR CHAR ( 3 ) ;
		DECLARE CHRMONEDACTABENEFICIARIO CHAR ( 3 ) ;

		DECLARE DECTCCOMPRA DECIMAL ( 11 , 6 ) DEFAULT 0 ;
		DECLARE DECTCVENTA DECIMAL ( 11 , 6 ) DEFAULT 0 ;

		DECLARE VARMENSAJESMS VARCHAR ( 200 ) ;
		DECLARE INTCODERRORSMS INTEGER ;
		DECLARE VARMSJERRORSMS VARCHAR ( 1000 ) ;

		DECLARE CHRMONCTAPAGADOR CHAR ( 3 ) ;
		DECLARE CHRMONFACTPROVEEDOR CHAR ( 3 ) ;
		DECLARE CHRMONCTAPROVEEDOR CHAR ( 3 ) ;
		DECLARE INTOPCIONTC INTEGER DEFAULT 0 ;

		DECLARE DECMONTO DECIMAL ( 18 , 2 ) ;
		DECLARE CHRCODMONEDA CHAR ( 3 ) ;
		DECLARE NUMUSUARIO NUMERIC ( 12 , 0 ) ;

		DECLARE NUMLINEA NUMERIC ( 1 , 0 ) ;
		DECLARE NUMMONTOTRANSFERIDO NUMERIC ( 18 , 2 ) ;
		DECLARE CHRMONEDAORIGEN CHAR ( 3 ) ;
		DECLARE CHROPERACION CHAR ( 10 ) ;
		DECLARE NUMTASA NUMERIC ( 12 , 6 ) ;
		DECLARE NUMMONTOCONVERTIDO NUMERIC ( 18 , 2 ) ;
		DECLARE CHRMONEDADESTINO CHAR ( 3 ) ;
		DECLARE NUMTASANEGOCIADAEXCEDIDA NUMERIC ( 1 , 0 ) ;
		DECLARE CHRTIPOTASAUTILIZADA CHAR ( 1 ) ;
		DECLARE NUMTIPO NUMERIC ( 2 , 0 ) DEFAULT 0 ;

		DECLARE CHRMONEDACOMPRADA CHAR ( 3 ) DEFAULT '' ;
		DECLARE NUMMONTOCOMPRADO NUMERIC ( 18 , 2 ) DEFAULT 0 ;	
		DECLARE CHRWORKCOMPRA CHAR ( 1 ) DEFAULT '' ;
		DECLARE NUMTASADECOMPRA NUMERIC ( 12 , 6 ) DEFAULT 0 ;
		DECLARE NUMTASANEGOCIADAEXCEDIDACOMPRA NUMERIC ( 1 , 0 ) DEFAULT 0 ;
		DECLARE CHRTIPOTASAUTILIZADOCOMPRA VARCHAR ( 1 ) ;

		DECLARE CHRMONEDAVENDIDA CHAR ( 3 ) DEFAULT '' ;
		DECLARE NUMMONTOVENDIDO NUMERIC ( 18 , 2 ) DEFAULT 0 ;	
		DECLARE CHRWORKVENTA CHAR ( 1 ) DEFAULT '' ;
		DECLARE NUMTASADEVENTA NUMERIC ( 12 , 6 ) DEFAULT 0 ;
		DECLARE NUMTASANEGOCIADAEXCEDIDAVENTA NUMERIC ( 1 , 0 ) DEFAULT 0 ;
		DECLARE CHRTIPOTASAUTILIZADOVENTA VARCHAR ( 1 ) ;

		DECLARE CHRIDUNICOFACTURA NUMERIC ( 12 , 0 ) ;
		DECLARE NUMMONTOCOMISION NUMERIC ( 15 , 4 ) ;
		DECLARE NUMMONTOIMPUESTO NUMERIC ( 15 , 4 ) ;
		DECLARE NUMTASASEGURIDAD NUMERIC ( 11 , 6 ) ;
		DECLARE CHRDESCRIPCIONCREDITO CHAR ( 130 ) ;
		DECLARE CHRCORREOSACK1 CHAR ( 100 ) ;
		DECLARE CHRCORREOSACK2 CHAR ( 100 ) ;
		DECLARE CHRDIRECCIONBENEF CHAR ( 200 ) ;
		DECLARE CHRCIUDADBENEF CHAR ( 200 ) ;
		DECLARE CHRNOMBREBANCO CHAR ( 35 ) ;
		DECLARE CHRDIRECCIONBANCO CHAR ( 35 ) ;
		DECLARE CHRCIUDADBANCO CHAR ( 35 ) ;
		DECLARE CHRBENEFICIARIOTIPOBANCO CHAR ( 1 ) ;
		DECLARE CHRBENEFICIARIOBANCO CHAR ( 12 ) ;
		DECLARE CHRCIUDADBANCOINTERM CHAR ( 250 ) ;
		DECLARE CHRNOMBBANCOINTERM CHAR ( 250 ) ;
		DECLARE CHRDIRECBANCOINTERM CHAR ( 250 ) ;
		DECLARE CHRNUMCUENTABANCOINTERM CHAR ( 250 ) ;
		DECLARE CHRTIPOBANCOINTERM CHAR ( 1 ) ;
		DECLARE CHRBANCOINTERM CHAR ( 15 ) ;
		DECLARE CHRGASTOSCUENTA CHAR ( 1 ) ;
		DECLARE CHRGASTOSCUENTAORDENANTE CHAR ( 1 ) DEFAULT '' ;
		DECLARE CHRGASTOSCUENTABENEFICIARIO CHAR ( 1 ) DEFAULT '' ;
		DECLARE NUMGASTOSBANCOCORRESPONSAL NUMERIC ( 15 , 4 ) ;
		DECLARE CHRGLTRANSACCION CHAR ( 35 ) ;
		DECLARE CHRGLCOMISION CHAR ( 35 ) ;
		DECLARE CHRGLGASTOSCORRESPONSAL CHAR ( 35 ) ;
		DECLARE CHRDOCUMENTOIDENTIDADBENEFICIARIO CHAR ( 35 ) ;
		DECLARE CHRNOMBREORDENANTE CHAR ( 200 ) ;
		DECLARE CHRMONEDACUENTAPAGADOR CHAR ( 3 ) ;
		DECLARE DECTELEFONOPAGADOR DECIMAL ( 11 ) ;
		DECLARE VARNUMEROREFERENCIA VARCHAR ( 6 ) ;
		DECLARE DECCENTROCOSTODEBITO DECIMAL ( 8 , 0 ) DEFAULT 0 ;
		DECLARE DECBATCHNUMBER DECIMAL ( 5 , 0 ) DEFAULT 961 ;
		DECLARE NUMCLIENTID NUMERIC ( 12 , 0 ) DEFAULT 0 ;
		DECLARE CHRCUENTABENEFICIARIO CHAR ( 35 ) ;

		
		DECLARE DECMONTODEBITOCOMISION DECIMAL ( 18 , 2 ) DEFAULT 0 ;
		DECLARE DECMONTOCREDITOCOMISION DECIMAL ( 18 , 2 ) DEFAULT 0 ;
		DECLARE DECMONTODEBITOCOMISIONTEMP DECIMAL ( 18 , 2 ) DEFAULT 0 ;
		DECLARE DECMONTOCREDITOCOMISIONTEMP DECIMAL ( 18 , 2 ) DEFAULT 0 ;

		DECLARE DECMONTODEBITOGASTOCORRESPONSAL DECIMAL ( 18 , 2 ) DEFAULT 0 ;
		DECLARE DECMONTOCREDITOGASTOCORRESPONSAL DECIMAL ( 18 , 2 ) DEFAULT 0 ;
		DECLARE DECMONTODEBITOGASTOCORRESPONSALTEMP DECIMAL ( 18 , 2 ) DEFAULT 0 ;
		DECLARE DECMONTOCREDITOGASTOCORRESPONSALTEMP DECIMAL ( 18 , 2 ) DEFAULT 0 ;
		DECLARE INTTIPOCOMISION SMALLINT ;
		DECLARE INTFEATUREID INTEGER DEFAULT 53 ; --TRANSFERENCIA INTERNACIONAL 
		DECLARE CHRTIPOCLIENTE CHAR ( 3 ) ;
		DECLARE INTSITETYPEID SMALLINT ;
		DECLARE INTSUBSIDIARYID INTEGER DEFAULT 4 ; --HONDURAS 
		DECLARE INTCORRESPONDENTBANKTYPESID SMALLINT ;
		DECLARE CHRICMONEDACUENTAPAGADOR CHAR ( 10 ) ;
		DECLARE CHRICMONEDACUENTABENEFICIARIO CHAR ( 10 ) ;
		DECLARE NUMMINVALUE NUMERIC ( 18 , 2 ) ;
		DECLARE NUMMAXVALUE NUMERIC ( 18 , 2 ) ;

		DECLARE NUMIDUNICOFACTURA_ANT NUMERIC ( 12 , 0 ) ;

		--2. Declarmos Cursores 
--=======================================================================================	 
		DECLARE CURTASAINVERTIDO CURSOR FOR
		SELECT * FROM TABLE ( BLHSRVLIB . FN_SE_SEL_TASASCAMBIOCLIENTEINVERTIDO ( NUMUSUARIO , DECMONTO , CHRCODMONEDA , CHRMONEDACTAPAGADOR , DECTCCOMPRA , DECTCVENTA ) ) AS T ;
		
		DECLARE CURTASANORMAL CURSOR FOR
		SELECT * FROM TABLE ( BLHSRVLIB . FN_SE_SEL_TASASCAMBIOCLIENTE ( NUMUSUARIO , DECMONTO , CHRCODMONEDA , CHRMONEDACTAPAGADOR , DECTCCOMPRA , DECTCVENTA ) ) AS T ;
		

		--3. Manejo de Errores 
--======================================================================================= 
		DECLARE CONTINUE HANDLER FOR NOT FOUND
		BEGIN
			SET INTSINREGISTROS = 1 ;
		END ;

		DECLARE CONTINUE HANDLER FOR SQLSTATE '75000'
		BEGIN
		
			SET CHRPROSEGUIR = 'N' ;
			SET INTTIPORESULTADO = INTCODIGOERROR ;
			SET VARMENSAJERESULTADO = BLHSRVLIB . FN_SE_SEL_ERROR ( LPAD ( INTTIPORESULTADO , 4 , '0' ) ) ;

		END ;
		
		DECLARE EXIT HANDLER FOR SQLSTATE '75002'
		BEGIN
			SET CHRPROSEGUIR = 'N' ;
			SET VARMENSAJERESULTADO = BLHSRVLIB . FN_SE_SEL_ERROR ( LPAD ( INTTIPORESULTADO , 4 , '0' ) ) ;
		END ;

		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS EXCEPTION 1 VARMENSAJERESULTADO = MESSAGE_TEXT ;
			SET CHRPROSEGUIR = 'N' ;
			SET INTTIPORESULTADO = - 1 ;
		END ;
		
		--4. Tablas temporales 
		--=======================================================================================	 
		DECLARE GLOBAL TEMPORARY TABLE PGLOGPROCESOTMP
		LIKE BLHCYFILES . TB_SE_TRN_PGLOGPROCESO
		ON COMMIT PRESERVE ROWS
		NOT LOGGED
		ON ROLLBACK PRESERVE ROWS ;
		
		DECLARE GLOBAL TEMPORARY TABLE PGCOLANOTIFICACIONESTMP
		LIKE BLHCYFILES . TB_SE_TRN_PGNOTIFICACIONES
		ON COMMIT PRESERVE ROWS
		NOT LOGGED
		ON ROLLBACK PRESERVE ROWS ;

		

		--5. Seteamos las variables declarados 
		--=======================================================================================	 
		SET INTTIPORESULTADO = 0 , VARMENSAJERESULTADO = 'NO ENTRO AL CICLO' , INTCONTADORFACTOK = 0 , INTTOTALFACT = 0 , DECMONTODEBITO = 0 , DECMONTOCREDITO = 0 ,
		CHRMONEDACTAPAGADOR = '' , CHRMONEDACTABENEFICIARIO = '' , NUMNUMEROSEGURIDAD = 0 , CHRPROSEGUIR = 'S' , NUMSALDODISPONIBLECUENTA = 0 , DECMONTODEBITOTEMP = 0 ,
		DECMONTOCREDITOTEMP = 0 , VARMSJERRORSMS = '' ;


		IF EXISTS ( SELECT 1 FROM QSYS2 . SYSTABLES WHERE TABLE_SCHEMA = 'BLHBUFILES' AND TABLE_NAME = 'BREOD' ) THEN
			SET INTTIPORESULTADO = 105 ;
			SIGNAL SQLSTATE '75002' ;
		END IF ;
	
		DELETE FROM SESSION . PGCOLANOTIFICACIONESTMP ;
		DELETE FROM SESSION . PGLOGPROCESOTMP ;

		SELECT DATE ( CAST ( CNTRDY + 2000 AS CHAR ( 4 ) ) || '-' || CNTRDM || '-' || CNTRDD )
		INTO DATFECHAACTUAL
		FROM BLHSRVLIB . A_CNTRLCNT ;

		SET INTSINREGISTROS = 0 ;

		IF INUMIDREFENCIA > 0 AND INUMCIFPAGADOR > 0 THEN
			
			SET INTESTADOPROCESO = 2 ;

			UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
			SET ESTADOFACTURA = 4 , ESTADOPROCESO = INTESTADOPROCESO
			WHERE IDREFERENCIA = INUMIDREFENCIA
			AND CIFPAGADOR = INUMCIFPAGADOR
			AND ESTADOFACTURA = 3
			AND FECHAPAGO = DATFECHAACTUAL
			AND TIENEDEBITOINMEDIATO = 'S'
			AND FORMAPAGO = 3 ;		

		ELSE

			SET INTESTADOPROCESO = 1 ;
			
			UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
			SET ESTADOFACTURA = 4 , ESTADOPROCESO = INTESTADOPROCESO
			WHERE ESTADOFACTURA IN ( 3 , 10 , 11 )
			AND FECHAPAGO <= DATFECHAACTUAL
			AND FORMAPAGO = 3 ;

		END IF ;

		IF INTSINREGISTROS = 0 THEN
			
			--** Se aplican los cambios de estado. 
			COMMIT ;

			SET INTSINREGISTROS = 0 ;
			
			--** Se toma la tasa de cambio C/V y tasa oficial USD 
			SELECT RATFPR , RATFSR , RATEXR INTO DECTCUSDCOMPRA , DECTCUSDVENTA , DECTCUSDOFICIAL
			FROM BLHSRVLIB . A_RATES
			WHERE RATCCY = 'USD' ;
			
			IF INTSINREGISTROS = 1 THEN
			
				SET INTTIPORESULTADO = 102 ;
				SET VARMENSAJERESULTADO = BLHSRVLIB . FN_SE_SEL_ERROR ( LPAD ( INTTIPORESULTADO , 4 , '0' ) ) ;
				SET CHRPROSEGUIR = 'N' ;
			
			ELSE
			
				SET INTSINREGISTROS = 0 ;
				
				--** Se toma la tasa de cambio C/V EUR 
				SELECT RATFPR , RATFSR INTO DECTCEURCOMPRA , DECTCEURVENTA
				FROM BLHSRVLIB . A_RATES
				WHERE RATCCY = 'EUR' ;

				IF INTSINREGISTROS = 1 THEN
				
					SET INTTIPORESULTADO = 103 ;
					SET VARMENSAJERESULTADO = BLHSRVLIB . FN_SE_SEL_ERROR ( LPAD ( INTTIPORESULTADO , 4 , '0' ) ) ;
					SET CHRPROSEGUIR = 'N' ;
				
				ELSE
				
					SET INTSINREGISTROS = 0 ;
					
					SELECT CNTBCU INTO CHRMONEDABASE
					FROM BLHSRVLIB . A_CNTRLCNT WHERE CNTKEY = '01' LIMIT 1 ;
					
					IF INTSINREGISTROS = 1 THEN
					
						SET INTTIPORESULTADO = 104 ;
						SET VARMENSAJERESULTADO = BLHSRVLIB . FN_SE_SEL_ERROR ( LPAD ( INTTIPORESULTADO , 4 , '0' ) ) ;
						SET CHRPROSEGUIR = 'N' ;
						
					END IF ;
		
				END IF ;
				
			END IF ;

		ELSE

			SET INTTIPORESULTADO = 109 ;
			SET VARMENSAJERESULTADO = BLHSRVLIB . FN_SE_SEL_ERROR ( LPAD ( INTTIPORESULTADO , 4 , '0' ) ) ;
			SET CHRPROSEGUIR = 'N' ;			

		END IF ;
		
		IF CHRPROSEGUIR = 'S' THEN

			--SET VarMensajeResultado = '' ; 
			--** Ciclo de facturas 
			FACT_LOOP : FOR CICLOFACTURAS AS FACTURAS CURSOR WITH HOLD FOR
				SELECT F . IDUNICOFACTURA , F . IDSITIO , F . IDUNICOBENEFICIARIO , F . MONEDAFACTURA , F . MONTO ,
					F . FECHAEMISION , F . FECHAPAGO , F . ESTADOFACTURA , F . REFERENCIA , F . FORMAPAGO , F . TIPOCANCELACION ,
					F . CTAPAGADOR , F . CIFPAGADOR , F . CUENTABENEFICIARIO , F . MONEDACUENTABENEFICIARIO ,
					F . CIFBENEFICIARIO , F . NOMBREBENEFICIARIO , F . CELULARBENEFICIARIO , REPLACE ( IFNULL ( AA . TIPO , 0 ) , 0 , 1 ) TIPO ,
					F . DOCUMENTOIDENTIDADBENEFICIARIO , F . BANCOBENEFICIARIO
				FROM BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS F
				LEFT JOIN BLHCYFILES . TB_SE_TRN_PGADELANTOSANTICIPOS AA ON AA . IDUNICOFACTURA = F . IDUNICOFACTURA AND AA . CODIGOESTADO = 6
				WHERE F . FECHAPAGO <= DATFECHAACTUAL
				AND F . ESTADOFACTURA = 4
				AND F . ESTADOPROCESO = INTESTADOPROCESO
				AND F . FORMAPAGO = 3
				ORDER BY F . CTAPAGADOR , F . IDUNICOBENEFICIARIO , F . FORMAPAGO , F . MONEDAFACTURA , AA . TIPO , F . FECHAPAGO , F . IDSITIO
			DO

				SET NUMIDUNICOFACTURA = CICLOFACTURAS.IDUNICOFACTURA ;

				CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - IDUNICOFACTURA: ' || NUMIDUNICOFACTURA || ' | MONEDAFACTURA: ' || MONEDAFACTURA || ' | MONTO: ' || MONTO || ' | FECHAEMISION: ' || FECHAEMISION || ' | FECHAPAGO: ' || FECHAPAGO || ' | ESTADOFACTURA: ' || ESTADOFACTURA || ' | FORMAPAGO: ' || FORMAPAGO || ' | CTAPAGADOR: ' || CTAPAGADOR || ' | CIFPAGADOR: ' || CIFPAGADOR || ' | MONEDACUENTABENEFICIARIO: ' || MONEDACUENTABENEFICIARIO || ' | CUENTABENEFICIARIO: ' || CUENTABENEFICIARIO || ' | TIPO: ' || TIPO );

				IF (NUMCTAPAGADOR_ANT IS NULL OR NUMCTAPAGADOR_ANT <> CICLOFACTURAS.CTAPAGADOR OR NUMIDBENEFICIARIO_ANT <> CICLOFACTURAS.IDUNICOBENEFICIARIO OR
					NUMFORMAPAGO_ANT <> CICLOFACTURAS.FORMAPAGO OR CHRMONEDAFACTURA_ANT <> CICLOFACTURAS.MONEDAFACTURA OR NUMTIPO <> TIPO) THEN

					SET CHRPROSEGUIR = 'S' ;

					IF NUMCTAPAGADOR_ANT IS NOT NULL IF DECMONTODEBITO > 0 THEN

						IF NUMFORMAPAGO_ANT = 3 AND NUMTIPO <> 2 THEN

							SET VARDESCRIPCIONDEBITO = SUBSTRING ( TRIM ( VARNOMBREBENEFICIARIO ) || ' ' || CAST ( INTCONTADORFACTOK AS VARCHAR ( 30 ) ) || ' FACTURAS' , 0 , 30 ) ;
							
							CALL BLHSRVLIB . SP_SE_SEL_NOMBRECIFPAGADOR ( NUMCIFPAGADOR , VARNOMBREPAGADOR , INTCODIGOERROR , VARMENSAJERESULTADO ) ;

							IF INTCODIGOERROR <> 0 OR TRIM ( VARNOMBREPAGADOR ) = '' THEN
								SET VARNOMBREPAGADOR = 'PAGANET' ;
							END IF ;
							
							SET VARDESCRIPCIONCREDITO = SUBSTRING ( TRIM ( VARNOMBREPAGADOR ) || ' ' || CAST ( INTCONTADORFACTOK AS VARCHAR ( 30 ) ) || ' FACTURAS' , 0 , 30 ) ;

							--SET VARMENSAJERESULTADO = 'CTA PAGADOR: ' || NUMCTAPAGADOR_ANT || ' - CTA BENEFICIARIO: ' || CHRCUENTABENEFICIARIO ;

							--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
							--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMENSAJERESULTADO ) ;

							--SET VARMENSAJERESULTADO = 'CIF PAGADOR: ' || NUMCIFPAGADOR || ' - CIF BENEFICIARIO: ' || NUMCIFBENEFICIARIO ;
							
							--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
							--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMENSAJERESULTADO ) ;

							
							--PROCESO  STI PAGANET BENEFICIARIO INTERNACIONAL (TEMPORALMENTE PROCESO IBS HOY EN DIA)
							SELECT IDUNICOFACTURA , MONTOCOMISION , MONTOIMPUESTO , TASASEGURIDAD , DESCRIPCIONCREDITO , CORREOSACK1 , CORREOSACK2 , DIRECCIONBENEF , CIUDADBENEF , NOMBREBANCO ,
							DIRECCIONBANCO , CIUDADBANCO , BENEFICIARIOTIPOBANCO , BENEFICIARIOBANCO , CIUDADBANCOINTERM , NOMBBANCOINTERM , DIRECBANCOINTERM , NUMCUENTABANCOINTERM , TIPOBANCOINTERM ,
							BANCOINTERM , GASTOSCUENTA , GASTOSBANCOCORRESPONSAL , GLTRANSACCION , GLCOMISION , GLGASTOSCORRESPONSAL , CLIENTID

								INTO CHRIDUNICOFACTURA , NUMMONTOCOMISION , NUMMONTOIMPUESTO , NUMTASASEGURIDAD , CHRDESCRIPCIONCREDITO , CHRCORREOSACK1 , CHRCORREOSACK2 , CHRDIRECCIONBENEF , CHRCIUDADBENEF , CHRNOMBREBANCO ,
							CHRDIRECCIONBANCO , CHRCIUDADBANCO , CHRBENEFICIARIOTIPOBANCO , CHRBENEFICIARIOBANCO , CHRCIUDADBANCOINTERM , CHRNOMBBANCOINTERM , CHRDIRECBANCOINTERM , CHRNUMCUENTABANCOINTERM , CHRTIPOBANCOINTERM ,
							CHRBANCOINTERM , CHRGASTOSCUENTA , NUMGASTOSBANCOCORRESPONSAL , CHRGLTRANSACCION , CHRGLCOMISION , CHRGLGASTOSCORRESPONSAL , NUMCLIENTID
								FROM BLHCYFILES . TB_SE_TRN_PGFACTURASEXTERIOR
								WHERE IDUNICOFACTURA = NUMIDUNICOFACTURA_ANT LIMIT 1 ;

							CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA_ANT , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR L396 - CHRIDUNICOFACTURA: ' || NUMIDUNICOFACTURA_ANT || ' | NUMTASASEGURIDAD: ' || NUMTASASEGURIDAD || ' | CHRDESCRIPCIONCREDITO: ' || CHRDESCRIPCIONCREDITO || ' | CHRNOMBREBANCO: ' || CHRNOMBREBANCO || ' | CHRBENEFICIARIOTIPOBANCO: ' || CHRBENEFICIARIOTIPOBANCO || ' | CHRNUMCUENTABANCOINTERM: ' || CHRNUMCUENTABANCOINTERM || ' | CHRTIPOBANCOINTERM: ' || CHRTIPOBANCOINTERM || ' | CHRBANCOINTERM: ' || CHRBANCOINTERM || ' | CHRGLTRANSACCION: ' || CHRGLTRANSACCION || ' | CHRGLCOMISION: ' || CHRGLCOMISION || ' | CHRGLGASTOSCORRESPONSAL: ' || CHRGLGASTOSCORRESPONSAL || ' | NUMCLIENTID: ' || NUMCLIENTID );

							--MONEDA CUENTA PAGADOR 
							SET CHRMONEDACUENTAPAGADOR = ( SELECT ACMCCY FROM BLHCYFILES . ACMST WHERE ACMACC = NUMCTAPAGADOR_ANT FETCH FIRST 1 ROW ONLY ) ;
							
							--Telefono CUSPHN 
							SELECT CUSNA1 , CUSPHN INTO CHRNOMBREORDENANTE , DECTELEFONOPAGADOR FROM BLHCYFILES . CUMST WHERE CUSCUN = CIFPAGADOR ;

							--TODO IDENTIFICAR LA DIRECCION DE LA TRANSACCION EN ESTE CASO SE DEJO I PERO DE SEBE VERIFICAR QUE VALOR RECIBIRA 
							--OBTENER EL CENTRO DE COSTO 
							SELECT ACMCCN INTO DECCENTROCOSTODEBITO FROM BLHSRVLIB . A_ACMST WHERE ACMACC = NUMCTAPAGADOR_ANT FETCH FIRST 1 ROWS ONLY ;

							-- COMMISSIONTYPEID 
							-- 1 : PORCENTAJE 
							-- 2 : MONTO FIJO 
							--CONVERSION CODIGO MONEDA IC 
							IF CHRMONEDACUENTAPAGADOR = 'LPS' THEN
								SET CHRICMONEDACUENTAPAGADOR = 558 ;
							ELSEIF CHRMONEDACUENTAPAGADOR = 'USD' THEN
								SET CHRICMONEDACUENTAPAGADOR = 840 ;
							ELSEIF CHRMONEDACUENTAPAGADOR = 'EUR' THEN
								SET CHRICMONEDACUENTAPAGADOR = 978 ;
							END IF ;


							IF MONEDACUENTABENEFICIARIO = 'LPS' THEN
								SET CHRICMONEDACUENTABENEFICIARIO = 558 ;
							ELSEIF MONEDACUENTABENEFICIARIO = 'USD' THEN
								SET CHRICMONEDACUENTABENEFICIARIO = 840 ;
							ELSEIF MONEDACUENTABENEFICIARIO = 'EUR' THEN
								SET CHRICMONEDACUENTABENEFICIARIO = 978 ;
							END IF ;

							--VALIDACION TIPO BANCO CORRESPONSAL
							IF CHRTIPOBANCOINTERM = 'D' THEN
								SET INTCORRESPONDENTBANKTYPESID = 1 ;
							END IF ;

							IF CHRTIPOBANCOINTERM = 'A' THEN
								SET INTCORRESPONDENTBANKTYPESID = 2 ;
							END IF ;

							--CALCULOMONTO DEBITO - CREDITO COMISION 
							IF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_SITE_COMMISSIONS WHERE CLIENTID = NUMCLIENTID AND CURRENCYID = CHRICMONEDACUENTAPAGADOR
								AND SUBSIDIARYID = INTSUBSIDIARYID AND FEATUREID = INTFEATUREID ) > 0 THEN

									SET ( DECMONTODEBITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_SITE_COMMISSIONS WHERE CLIENTID = NUMCLIENTID
										AND CURRENCYID = CHRICMONEDACUENTAPAGADOR AND SUBSIDIARYID = INTSUBSIDIARYID AND FEATUREID = INTFEATUREID FETCH FIRST 1 ROW ONLY ) ;

									IF INTTIPOCOMISION = 1 THEN
										SET DECMONTODEBITOCOMISION = ( ( DECMONTODEBITOCOMISIONTEMP / 100 ) * DECMONTODEBITO ) ;
									ELSE
										SET DECMONTODEBITOCOMISION = DECMONTODEBITOCOMISIONTEMP ;
									END IF ;

									SET ( DECMONTOCREDITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_SITE_COMMISSIONS WHERE CLIENTID = NUMCLIENTID
										AND CURRENCYID = CHRICMONEDACUENTABENEFICIARIO AND SUBSIDIARYID = INTSUBSIDIARYID AND FEATUREID = INTFEATUREID FETCH FIRST 1 ROW ONLY ) ;

									IF INTTIPOCOMISION = 1 THEN
										SET DECMONTOCREDITOCOMISION = ( ( DECMONTOCREDITOCOMISIONTEMP / 100 ) * DECMONTOCREDITO ) ;
									ELSE
										SET DECMONTOCREDITOCOMISION = DECMONTOCREDITOCOMISIONTEMP ;
									END IF ;


							ELSEIF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_GLOBAL_COMMISSIONS WHERE SUBSIDIARYID = INTSUBSIDIARYID AND CURRENCYID = CHRICMONEDACUENTAPAGADOR AND FEATUREID = INTFEATUREID ) > 0 THEN

									SET ( DECMONTODEBITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_GLOBAL_COMMISSIONS
										WHERE SUBSIDIARYID = INTSUBSIDIARYID AND CURRENCYID = CHRICMONEDACUENTAPAGADOR AND FEATUREID = INTFEATUREID AND COMMISSIONVALUE > 0 FETCH FIRST 1 ROW ONLY ) ;

									IF INTTIPOCOMISION = 1 THEN
										SET DECMONTODEBITOCOMISION = ( ( DECMONTODEBITOCOMISIONTEMP / 100 ) * DECMONTODEBITO ) ;
									ELSE
										SET DECMONTODEBITOCOMISION = DECMONTODEBITOCOMISIONTEMP ;
									END IF ;

									SET ( DECMONTOCREDITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_GLOBAL_COMMISSIONS
										WHERE SUBSIDIARYID = INTSUBSIDIARYID AND CURRENCYID = CHRICMONEDACUENTABENEFICIARIO AND FEATUREID = INTFEATUREID AND COMMISSIONVALUE > 0 FETCH FIRST 1 ROW ONLY ) ;

									IF INTTIPOCOMISION = 1 THEN
										SET DECMONTOCREDITOCOMISION = ( ( DECMONTODEBITOCOMISIONTEMP / 100 ) * DECMONTOCREDITO ) ;

									ELSE
										SET DECMONTOCREDITOCOMISION = DECMONTOCREDITOCOMISIONTEMP ;
									END IF ;
							END IF ;

							IF INTTIPOCOMISION = 1 THEN
								IF DECMONTODEBITOCOMISION < NUMMINVALUE THEN
									SET DECMONTODEBITOCOMISION = NUMMINVALUE ;
								ELSEIF DECMONTODEBITOCOMISION > NUMMAXVALUE THEN
									SET DECMONTODEBITOCOMISION = NUMMAXVALUE ;
								END IF ;

								IF DECMONTOCREDITOCOMISION < NUMMINVALUE THEN
									SET DECMONTOCREDITOCOMISION = NUMMINVALUE ;
								ELSEIF DECMONTOCREDITOCOMISION > NUMMAXVALUE THEN
									SET DECMONTOCREDITOCOMISION = NUMMAXVALUE ;
								END IF ;
							END IF ;

							--CALCULO MONTO DEBITO - CREDITO GASTO CORRESPONSAL 
							IF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_SITECORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR
								AND SUBSIDIARYID = INTSUBSIDIARYID AND CLIENTID = NUMCLIENTID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID ) > 0 THEN

									SET DECMONTODEBITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_SITECORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR
									AND SUBSIDIARYID = INTSUBSIDIARYID AND CLIENTID = NUMCLIENTID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;

									SET DECMONTOCREDITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_SITECORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTABENEFICIARIO
									AND SUBSIDIARYID = INTSUBSIDIARYID AND CLIENTID = NUMCLIENTID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;

							ELSEIF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_GLOBALCORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR
								AND SUBSIDIARYID = INTSUBSIDIARYID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID ) > 0 THEN

									SET DECMONTODEBITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_GLOBALCORRESPONDENTBANKEXPENSES
										WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR AND SUBSIDIARYID = INTSUBSIDIARYID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;

									SET DECMONTOCREDITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_GLOBALCORRESPONDENTBANKEXPENSES
										WHERE CURRENCYID = CHRICMONEDACUENTABENEFICIARIO AND SUBSIDIARYID = INTSUBSIDIARYID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;
							END IF ;

							CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA_ANT , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - Parametros SP_SE_VAR_TRANSFERENCIAEXTERIOR1 - CHRIDUNICOFACTURA: ' || NUMIDUNICOFACTURA_ANT || ' | NUMCIFPAGADOR: ' || NUMCIFPAGADOR || ' | NUMCTAPAGADOR_ANT: ' || NUMCTAPAGADOR_ANT || ' | CHRGLTRANSACCION: ' || CHRGLTRANSACCION || ' | CHRMONEDACUENTAPAGADOR: ' || CHRMONEDACUENTAPAGADOR || ' | CHRCUENTABENEFICIARIO: ' || CHRCUENTABENEFICIARIO || ' | CHRMONEDACTABENEFICIARIO: ' || CHRMONEDACTABENEFICIARIO || ' | DECMONTODEBITO: ' || DECMONTODEBITO || ' | CHRDESCRIPCIONCREDITO: ' || CHRDESCRIPCIONCREDITO || ' | CHRBANCOINTERM: ' || CHRBANCOINTERM || ' | CHRNUMCUENTABANCOINTERM: ' || CHRNUMCUENTABANCOINTERM );

							CALL BLHSRVLIB . SP_SE_VAR_TRANSFERENCIAEXTERIOR ( NUMCIFPAGADOR , NUMIDUNICOFACTURA_ANT , NUMCTAPAGADOR_ANT , CHRGLTRANSACCION , CHRMONEDACUENTAPAGADOR ,
							CHRCUENTABENEFICIARIO , CHRMONEDACTABENEFICIARIO , VARNOMBREBENEFICIARIO , CHRDIRECCIONBENEF , CHRCIUDADBENEF ,
							CHRBENEFICIARIOTIPOBANCO , CHRBENEFICIARIOBANCO , CHRNOMBREBANCO , CHRDIRECCIONBANCO , CHRCIUDADBANCO ,
							DECMONTODEBITO , DECMONTODEBITO , CHRDESCRIPCIONCREDITO , CHRGASTOSCUENTA , CHRNOMBREORDENANTE , CHRDOCUMENTOIDENTIDADBENEFICIARIO , DECTELEFONOPAGADOR , CHRCORREOSACK1 ,
							CHRCORREOSACK2 , DECTCUSDCOMPRA , DECTCUSDVENTA , NUMGASTOSBANCOCORRESPONSAL , NUMMONTOCOMISION , NUMTASASEGURIDAD , CHRTIPOBANCOINTERM ,
							CHRBANCOINTERM , CHRNOMBBANCOINTERM , CHRDIRECBANCOINTERM , CHRCIUDADBANCOINTERM , CHRCIUDADBANCOINTERM ,
							CHRNUMCUENTABANCOINTERM , VARNUMEROREFERENCIA , INTTIPORESULTADO , VARMENSAJERESULTADO ) ;

							CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA_ANT , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - Resultado SP_SE_VAR_TRANSFERENCIAEXTERIOR1 - CHRIDUNICOFACTURA: ' || NUMIDUNICOFACTURA_ANT || ' | INTTIPORESULTADO: ' || INTTIPORESULTADO || ' | VARMENSAJERESULTADO: ' || VARMENSAJERESULTADO );

							IF INTTIPORESULTADO <> 0 THEN
								SET INTTIPORESULTADO = INTTIPORESULTADO ;
								SET VARMENSAJERESULTADO = VARMENSAJERESULTADO ;
								SIGNAL SQLSTATE '75000' ;
							END IF ;
							--------------------------- 
							--MOVIMIENTOS TRANSACCION-- 
							--------------------------- 
							------------------- 
							--DEBITO COMISION-- 
							------------------- 
							----------------------------- 
							--DEBITO GASTO CORRESPONSAL-- 
							----------------------------- 

							--** Se guarda el mensaje original para poder marcar los registros de facturas en el log en caso de que no se aplique el movimiento final. 
							SET VARMENSAJE = VARMENSAJERESULTADO ;

							--SET VARMENSAJERESULTADO = 'RESULTADO LLAMADO PROCESO PAGO FACTURAS: ' || VARMENSAJERESULTADO || 'Numero Referencia: ' || VARNUMEROREFERENCIA ;							
							
							--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
							--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , DECMONTODEBITO , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , VARMENSAJERESULTADO ) ;

							IF INTTIPORESULTADO = 0 THEN
							
								IF VARCELULARBENEFICIARIO <> '' THEN

									SET VARMENSAJESMS = LEFT ( 'Pag@Net: ' || TRIM ( VARNOMBREPAGADOR ) || ' le ha CANCELADO el pago de factura(s) por un monto de ' || CHRMONEDAFACTURA_ANT || ' ' || DECMONTOCREDITO || ' . Para mayor información ingrese a Banc@Net. Gracias.' , 160 ) ;
								
									--** Enviar Notificacion SMS 
									CALL BLHSRVLIB . SP_SE_INS_SMS ( VARCELULARBENEFICIARIO , VARMENSAJESMS , 'PG' , 2 , 'PG' , '' , 0 , 3 , INTCODERRORSMS , VARMSJERRORSMS ) ;

									IF INTCODERRORSMS = 0 THEN
										SET VARMSJERRORSMS = 'SMS OK' ;
									ELSE
										SET VARMSJERRORSMS = LEFT ( 'SMS ERROR: ' || TRIM ( VARMSJERRORSMS ) , 1000 ) ;
									END IF ;

									INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
									VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMSJERRORSMS ) ;
								
								ELSE
									
									SET VARMSJERRORSMS = 'SIN  CELULAR' ;

									INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
									VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMSJERRORSMS ) ;

								END IF ;


								--** Se guarda en la tabla final del log los datos 
								INSERT INTO BLHCYFILES . TB_SE_TRN_PGLOGPROCESO
								SELECT * FROM SESSION . PGLOGPROCESOTMP ;
								
								--** Se guarda en la tabla final de notificaciones los datos 
								INSERT INTO BLHCYFILES . TB_SE_TRN_PGNOTIFICACIONES
								SELECT * FROM SESSION . PGCOLANOTIFICACIONESTMP ;
		
								COMMIT ;
								
								--** Se borran los registros guardados en las tablas temporales. 
								DELETE FROM SESSION . PGLOGPROCESOTMP ;
								DELETE FROM SESSION . PGCOLANOTIFICACIONESTMP ;
								
							ELSE
							
								ROLLBACK HOLD ;
								
								--** Se actualiza los registros de la tabla PGLOGPROCESOTMP para que la transacción quede con el error actualizado 
								UPDATE SESSION . PGLOGPROCESOTMP SET MENSAJEPROCESO = VARMENSAJE
								WHERE NUMEROGRUPO = NUMNUMEROSEGURIDAD
								AND CODTRANSACCION <> 0
								AND MENSAJEPROCESO = 'APLICADA' ;
								
								--** Se guarda en la tabla final del log los datos 
								INSERT INTO BLHCYFILES . TB_SE_TRN_PGLOGPROCESO
								SELECT * FROM SESSION . PGLOGPROCESOTMP ;
								
								--** Se guarda en la tabla final de notificaciones los datos 
								INSERT INTO BLHCYFILES . TB_SE_TRN_PGNOTIFICACIONES
								SELECT * FROM SESSION . PGCOLANOTIFICACIONESTMP ;
								
								COMMIT ;
								
								--** Se borran los registros guardados en las tablas temporales. 
								DELETE FROM SESSION . PGLOGPROCESOTMP ;
								DELETE FROM SESSION . PGCOLANOTIFICACIONESTMP ;
								
							END IF ;


						END IF ;

						--** Se inicializan variables acumuladoras 
						SET INTCONTADORFACTOK = 0 ;
						SET INTTOTALFACT = 0 ;
						SET DECMONTODEBITO = 0 ;
						SET DECMONTOCREDITO = 0 ;
						--SET DECMONTODBNUMSEG = DecMontoDebito ; 
					ELSE
						
						--** Se inicializan variables acumuladoras 
						SET INTCONTADORFACTOK = 0 ;
						SET INTTOTALFACT = 0 ;
						SET DECMONTODEBITO = 0 ;
						SET DECMONTOCREDITO = 0 ;
						--SET DECMONTODBNUMSEG = DecMontoDebito ; 
						--** Se guarda en la tabla final del log los datos 
						INSERT INTO BLHCYFILES . TB_SE_TRN_PGLOGPROCESO
						SELECT * FROM SESSION . PGLOGPROCESOTMP ;
						
						--** Se guarda en la tabla final de notificaciones los datos 
						INSERT INTO BLHCYFILES . TB_SE_TRN_PGNOTIFICACIONES
						SELECT * FROM SESSION . PGCOLANOTIFICACIONESTMP ;

						--** Se hace commit para que se apliquen los cambios en la tabla log. 						 
						COMMIT ;
						
						--** Se borran los registros guardados en las tablas temporales. 
						DELETE FROM SESSION . PGLOGPROCESOTMP ;
						DELETE FROM SESSION . PGCOLANOTIFICACIONESTMP ;
					END IF ;

					SET CHRHORA = REPLACE ( CAST ( CURRENT TIME AS VARCHAR ( 8 ) ) , '.' , '' ) ;
					
					--** Obtener numero seguridad interno 
					SELECT NEXTVAL FOR BLHSRVLIB . SECTRANSE INTO NUMNUMEROSEGURIDAD FROM SYSIBM . SYSDUMMY1 ;	
					
					IF NUMCTAPAGADOR_ANT IS NULL OR NUMCTAPAGADOR_ANT <> CTAPAGADOR THEN

						SET INTSINREGISTROS = 0 ;
						--Validar si la cuenta debito pertenece al cif pagador 
						--si tiene estado activo 
						SELECT ACMCUN , CASE WHEN ACMAST IN ( 'A' , ' ' ) THEN 'A' ELSE 'N' END , ACMCCY
						INTO DECCIF , CHRESTADO , CHRMONEDACTAPAGADOR
						FROM BLHSRVLIB . A_ACMST
						WHERE ACMACC = CTAPAGADOR ;
						
						--  Validaciones cuenta pagador 
						IF INTSINREGISTROS = 0 THEN
							IF CIFPAGADOR = DECCIF THEN
								IF CHRESTADO = 'N' THEN					
									SET INTCODIGOERROR = 52 ;
									SIGNAL SQLSTATE '75000' ;
								END IF ;
							ELSE
								SET INTCODIGOERROR = 99 ;
								SIGNAL SQLSTATE '75000' ;
							END IF ;
						ELSE
							SET INTCODIGOERROR = 98 ;
							SIGNAL SQLSTATE '75000' ;
						END IF ;

						IF CHRPROSEGUIR = 'S' THEN
							
							SET NUMSALDODISPONIBLECUENTA = BLHSRVLIB . FN_SE_SEL_SALDOCUENTA ( CTAPAGADOR ) ;

							IF NUMSALDODISPONIBLECUENTA <= 0 THEN
								SET INTCODIGOERROR = 181 ;
								SIGNAL SQLSTATE '75000' ;
							END IF ;

						END IF ;
						
					END IF ;

					SET INTSINREGISTROS = 0 ;

					SET CHRMONEDACTABENEFICIARIO = MONEDACUENTABENEFICIARIO ;
					SET CHRDOCUMENTOIDENTIDADBENEFICIARIO = DOCUMENTOIDENTIDADBENEFICIARIO ;

					SET NUMCTAPAGADOR_ANT = CTAPAGADOR ;
					SET NUMIDBENEFICIARIO_ANT = IDUNICOBENEFICIARIO ;
					SET NUMFORMAPAGO_ANT = FORMAPAGO ;
					SET CHRMONEDAFACTURA_ANT = MONEDAFACTURA ;
					SET NUMCIFPAGADOR = CIFPAGADOR ;
					SET NUMCIFBENEFICIARIO = CIFBENEFICIARIO ;
					SET CHRCUENTABENEFICIARIO = CUENTABENEFICIARIO ;
					SET VARNOMBREBENEFICIARIO = NOMBREBENEFICIARIO ;
					SET VARCELULARBENEFICIARIO = CELULARBENEFICIARIO ;
					SET NUMTIPO = TIPO ;
					SET NUMIDUNICOFACTURA = CICLOFACTURAS.IDUNICOFACTURA ;
					SET NUMIDUNICOFACTURA_ANT = CICLOFACTURAS.IDUNICOFACTURA;
					
					SELECT MONEDACTAPAGADOR , MONEDAFACTPROVEEDOR , MONEDACTAPROVEEDOR
					INTO CHRMONCTAPAGADOR , CHRMONFACTPROVEEDOR , CHRMONCTAPROVEEDOR
					FROM BLHSRVLIB . A_BRPGCTESEXCEPCIONES
					WHERE CODPAGADOR = NUMCIFPAGADOR ;

				END IF ;
				
				--** Se lleva el conteo de total de facturas por grupo 
				SET INTTOTALFACT = INTTOTALFACT + 1 ;

				CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - ANTES DE AGRUPAR' );	

				IF CHRPROSEGUIR = 'S' THEN

					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - COMIENZA A AGRUPAR' );	

					SET DECTCCOMPRA = 0 ;
					SET DECTCVENTA = 0 ;
					SET NUMTASADECOMPRA = 0 ;
					SET NUMTASADEVENTA = 0 ;

					IF CHRMONEDACTAPAGADOR <> MONEDAFACTURA THEN

						CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - VALIDA MONEDA AGRUPAR' );	


						IF CHRMONEDACTAPAGADOR = CHRMONCTAPAGADOR AND MONEDAFACTURA = CHRMONFACTPROVEEDOR AND CHRMONEDACTABENEFICIARIO = CHRMONCTAPROVEEDOR THEN

							SET DECMONTODEBITOTEMP = ROUND ( MONTO * DECTCUSDOFICIAL , 2 ) ;
							SET DECMONTOCREDITOTEMP = DECMONTODEBITOTEMP ;

							
							SET DECTCVENTA = DECTCUSDOFICIAL ;
							SET NUMTASADEVENTA = DECTCVENTA ;
							SET INTOPCIONTC = 0 ;
						
						ELSEIF CHRMONEDACTAPAGADOR = 'LPS' THEN
						
							IF MONEDAFACTURA = 'USD' THEN
								
								SET DECTCCOMPRA = DECTCUSDCOMPRA ;								
								SET DECTCVENTA = DECTCUSDVENTA ;
								SET INTOPCIONTC = 1 ;
								
							ELSE
							
								--**SET DecTcCompra = DECTCEURCOMPRA ; 
								SET DECTCVENTA = DECTCEURVENTA ;
								SET INTOPCIONTC = 1 ;
								
							END IF ;
							
						ELSEIF CHRMONEDACTAPAGADOR = 'USD' THEN
						
							IF MONEDAFACTURA <> CHRMONEDABASE THEN
							
								SET DECTCCOMPRA = DECTCUSDCOMPRA ;
								SET DECTCVENTA = DECTCEURVENTA ;
								SET INTOPCIONTC = 1 ;
								
							ELSE
							
								SET DECTCCOMPRA = DECTCUSDCOMPRA ;
								SET DECTCVENTA = DECTCUSDVENTA ;
								SET INTOPCIONTC = 1 ;
								
							END IF ;
							
						ELSEIF CHRMONEDACTAPAGADOR = 'EUR' THEN
						
							IF MONEDAFACTURA <> CHRMONEDABASE THEN
							
								SET DECTCCOMPRA = DECTCEURCOMPRA ;
								SET DECTCVENTA = DECTCUSDVENTA ;
								SET INTOPCIONTC = 1 ;
								
							ELSE
							
								SET DECTCCOMPRA = DECTCEURCOMPRA ;
								SET DECTCVENTA = DECTCEURVENTA ;
								SET INTOPCIONTC = 1 ;
								
							END IF ;
							
						END IF ;
						
						SET NUMUSUARIO = CIFPAGADOR ;
						SET DECMONTO = MONTO ;
						SET CHRCODMONEDA = MONEDAFACTURA ;	
			
						CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - PREVIO A INTOPCIONTC AGRUPAR' );
						
						IF INTOPCIONTC = 1 THEN						
							
							SET DECMONTOCREDITOTEMP = MONTO ;
							SET INTSINREGISTROS = 0 ;
							
							OPEN CURTASAINVERTIDO ;
							FETCH CURTASAINVERTIDO INTO NUMLINEA , NUMMONTOTRANSFERIDO , CHRMONEDAORIGEN , CHROPERACION , NUMTASA , NUMMONTOCONVERTIDO , CHRMONEDADESTINO , NUMTASANEGOCIADAEXCEDIDA , CHRTIPOTASAUTILIZADA ;
							
							WHILE INTSINREGISTROS = 0 DO
							
								IF CHROPERACION = 'COMPRA' THEN
									IF CHRMONEDADESTINO = CHRMONEDABASE THEN
										SET CHRMONEDACOMPRADA = CHRMONEDAORIGEN ;
									ELSE
										SET CHRMONEDACOMPRADA = CHRMONEDADESTINO ;
									END IF ;
									SET NUMMONTOCOMPRADO = NUMMONTOTRANSFERIDO ;
									SET CHRWORKCOMPRA = 'C' ;
									SET NUMTASADECOMPRA = NUMTASA ;
									SET NUMTASANEGOCIADAEXCEDIDACOMPRA = NUMTASANEGOCIADAEXCEDIDA ;
									SET CHRTIPOTASAUTILIZADOCOMPRA = CHRTIPOTASAUTILIZADA ;
									
									SET DECMONTODEBITOTEMP = NUMMONTOTRANSFERIDO ;
									
								ELSE
									IF CHRMONEDADESTINO = CHRMONEDABASE THEN
										SET CHRMONEDAVENDIDA = CHRMONEDAORIGEN ;
									ELSE
										SET CHRMONEDAVENDIDA = CHRMONEDADESTINO ;
									END IF ;
									SET NUMMONTOVENDIDO = NUMMONTOCONVERTIDO ;
									SET CHRWORKVENTA = 'V' ;
									SET NUMTASADEVENTA = NUMTASA ;
									SET NUMTASANEGOCIADAEXCEDIDAVENTA = NUMTASANEGOCIADAEXCEDIDA ;
									SET CHRTIPOTASAUTILIZADOVENTA = CHRTIPOTASAUTILIZADA ;
									
									SET DECMONTODEBITOTEMP = NUMMONTOTRANSFERIDO ;
									
								END IF ;
			
								FETCH CURTASAINVERTIDO INTO NUMLINEA , NUMMONTOTRANSFERIDO , CHRMONEDAORIGEN , CHROPERACION , NUMTASA , NUMMONTOCONVERTIDO , CHRMONEDADESTINO , NUMTASANEGOCIADAEXCEDIDA , CHRTIPOTASAUTILIZADA ;
								
							END WHILE ;
		
							CLOSE CURTASAINVERTIDO ;
							
						ELSEIF INTOPCIONTC = 2 THEN
						
							SET DECMONTOCREDITOTEMP = MONTO ;
							
							SET INTSINREGISTROS = 0 ;
							
							OPEN CURTASANORMAL ;
							FETCH CURTASANORMAL INTO NUMLINEA , NUMMONTOTRANSFERIDO , CHRMONEDAORIGEN , CHROPERACION , NUMTASA , NUMMONTOCONVERTIDO , CHRMONEDADESTINO , NUMTASANEGOCIADAEXCEDIDA , CHRTIPOTASAUTILIZADA ;
							
							WHILE INTSINREGISTROS = 0 DO
								
								IF CHROPERACION = 'COMPRA' THEN
									IF CHRMONEDADESTINO = CHRMONEDABASE THEN
										SET CHRMONEDACOMPRADA = CHRMONEDAORIGEN ;
									ELSE
										SET CHRMONEDACOMPRADA = CHRMONEDADESTINO ;
									END IF ;
									SET NUMMONTOCOMPRADO = NUMMONTOTRANSFERIDO ;
									SET CHRWORKCOMPRA = 'C' ;
									SET NUMTASADECOMPRA = NUMTASA ;
									SET NUMTASANEGOCIADAEXCEDIDACOMPRA = NUMTASANEGOCIADAEXCEDIDA ;
									SET CHRTIPOTASAUTILIZADOCOMPRA = CHRTIPOTASAUTILIZADA ;
																	
								ELSE
									IF CHRMONEDADESTINO = CHRMONEDABASE THEN
										SET CHRMONEDAVENDIDA = CHRMONEDAORIGEN ;
									ELSE
										SET CHRMONEDAVENDIDA = CHRMONEDADESTINO ;
									END IF ;
									SET NUMMONTOVENDIDO = NUMMONTOCONVERTIDO ;
									SET CHRWORKVENTA = 'V' ;
									SET NUMTASADEVENTA = NUMTASA ;
									SET NUMTASANEGOCIADAEXCEDIDAVENTA = NUMTASANEGOCIADAEXCEDIDA ;
									SET CHRTIPOTASAUTILIZADOVENTA = CHRTIPOTASAUTILIZADA ;
									
									SET DECMONTODEBITOTEMP = NUMMONTOCONVERTIDO ;
									
								END IF ;
			
								FETCH CURTASANORMAL INTO NUMLINEA , NUMMONTOTRANSFERIDO , CHRMONEDAORIGEN , CHROPERACION , NUMTASA , NUMMONTOCONVERTIDO , CHRMONEDADESTINO , NUMTASANEGOCIADAEXCEDIDA , CHRTIPOTASAUTILIZADA ;
								
							END WHILE ;
		
							CLOSE CURTASANORMAL ;
							
						END IF ;	

					ELSE
						SET DECMONTODEBITOTEMP = MONTO ;
						SET DECMONTOCREDITOTEMP = MONTO ;
					END IF ;


					SET NUMSALDODISPONIBLECUENTA = BLHSRVLIB . FN_SE_SEL_SALDOCUENTA ( CTAPAGADOR ) ;

					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - VALIDA SALDO AGRUPAR - NUMSALDODISPONIBLECUENTA: ' || NUMSALDODISPONIBLECUENTA );

					IF NUMSALDODISPONIBLECUENTA >= DECMONTODEBITOTEMP THEN

						IF NUMTIPO = 1 THEN
							--** Se actualiza saldo de la cuenta pagador						 
							/*CALL BLHSRVLIB . SP_SE_UPD_SALDODISPONIBLECUENTA ( CTAPAGADOR , DECMONTODEBITOTEMP , 'DB' , INTTIPORESULTADO , VARMENSAJERESULTADO ) ;   
    
							INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )   
							VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , NUMIDUNICOFACTURA , DECMONTODEBITOTEMP , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , 'SP_SE_UPD_SaldoDisponibleCuenta: ' || INTTIPORESULTADO || ' ' || VARMENSAJERESULTADO || ' ' || CHRPROSEGUIR ) ;   
								   
    
							IF INTTIPORESULTADO <> 0 THEN   
								SET CHRPROSEGUIR = 'N' ;   
							END IF ;*/

								
							IF CHRPROSEGUIR = 'S' THEN	
							
								--** Se obtiene la fecha y hora actual. 
								SELECT TIMESTAMP ( DATE ( CAST ( CNTRDY + 2000 AS CHAR ( 4 ) ) || '-' || CNTRDM || '-' || CNTRDD ) , CURRENT TIME )
								INTO TIMFECHAACTUAL
								FROM BLHSRVLIB . A_CNTRLCNT ;							
								
								--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
								--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , NUMIDUNICOFACTURA , DECMONTODEBITOTEMP , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , 'Despues obtener fecha: ' || INTTIPORESULTADO || ' ' || VARMENSAJERESULTADO || ' ' || CHRPROSEGUIR ) ;
								
								UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
								SET ESTADOFACTURA = ( CASE WHEN TIPOCANCELACION = 0	THEN 5
														WHEN TIPOCANCELACION = 1	THEN 8
														WHEN TIPOCANCELACION = 2 THEN 7
														WHEN TIPOCANCELACION = 3 THEN 12
														WHEN TIPOCANCELACION = 4 THEN 12
													END ) ,							
								NUMEROSEGURIDAD = NUMNUMEROSEGURIDAD ,
								FECHAPROCESO = TIMFECHAACTUAL ,
								TASACOMPRA = NUMTASADECOMPRA ,
								TASAVENTA = NUMTASADEVENTA ,
								MONTOCONVERTIDO = DECMONTODEBITOTEMP
								WHERE IDUNICOFACTURA = NUMIDUNICOFACTURA
								AND ESTADOFACTURA = 4 ;
	
								--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
								--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , NUMIDUNICOFACTURA , DECMONTODEBITOTEMP , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , 'Despues update factura: ' || INTTIPORESULTADO || ' ' || VARMENSAJERESULTADO || ' ' || CHRPROSEGUIR ) ;
																
								SET DECMONTODEBITO = DECMONTODEBITO + DECMONTODEBITOTEMP ;
								SET DECMONTOCREDITO = DECMONTOCREDITO + DECMONTOCREDITOTEMP ;
								
								--** Se lleva el conteo de total de facturas aplicadas 
								SET INTCONTADORFACTOK = INTCONTADORFACTOK + 1 ;	
								
								SET VARMENSAJERESULTADO = 'APLICADA' ;
								
							ELSE
								
								UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
								SET ESTADOPROCESO = 0 ,
								ESTADOFACTURA = ( CASE WHEN TIPOCANCELACION = 0	THEN 3
													WHEN TIPOCANCELACION = 2 THEN 7
													WHEN TIPOCANCELACION = 3 THEN 10
													WHEN TIPOCANCELACION = 4 THEN 11
												END )
								WHERE IDUNICOFACTURA = NUMIDUNICOFACTURA
								AND ESTADOFACTURA = 4 ;

							END IF ;
							
						ELSEIF NUMTIPO = 2 THEN
							
							IF EXISTS ( SELECT 1 FROM BLHCYFILES . DLPMT WHERE UNMF10 = NUMIDUNICOFACTURA ) THEN
								--** Grabar en la tabla temporal del log 
								INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
								VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , NUMIDUNICOFACTURA , DECMONTODEBITOTEMP , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , 'Cuota pendiente de pago por procesos del cierre' ) ;
							ELSE
									--** Se obtiene la fecha y hora actual. 
								SELECT TIMESTAMP ( DATE ( CAST ( CNTRDY + 2000 AS CHAR ( 4 ) ) || '-' || CNTRDM || '-' || CNTRDD ) , CURRENT TIME )
								INTO TIMFECHAACTUAL
								FROM BLHSRVLIB . A_CNTRLCNT ;
									
								UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
								SET ESTADOFACTURA = ( CASE WHEN TIPOCANCELACION = 0	THEN 5
														WHEN TIPOCANCELACION = 1	THEN 8
														WHEN TIPOCANCELACION = 2 THEN 7
														WHEN TIPOCANCELACION = 3 THEN 12
														WHEN TIPOCANCELACION = 4 THEN 12
													END ) ,							
								NUMEROSEGURIDAD = NUMNUMEROSEGURIDAD ,
								FECHAPROCESO = TIMFECHAACTUAL ,
								TASACOMPRA = NUMTASADECOMPRA ,
								TASAVENTA = NUMTASADEVENTA ,
								MONTOCONVERTIDO = DECMONTODEBITOTEMP
								WHERE IDUNICOFACTURA = NUMIDUNICOFACTURA
								AND ESTADOFACTURA = 4 ;
								
								INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
								VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , NUMIDUNICOFACTURA , DECMONTODEBITOTEMP , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , 'Cuota pendiente Cancelada, se actualiza estado factura' ) ;
								
							END IF ;
							
						END IF ;

					ELSE
						
						UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
						SET ESTADOPROCESO = 0 ,
							ESTADOFACTURA = ( CASE WHEN TIPOCANCELACION = 0	THEN 3
												WHEN TIPOCANCELACION = 2 THEN 7
												WHEN TIPOCANCELACION = 3 THEN 10
												WHEN TIPOCANCELACION = 4 THEN 11
											END )
						WHERE IDUNICOFACTURA = NUMIDUNICOFACTURA
						AND ESTADOFACTURA = 4 ;
						
						SET VARMENSAJERESULTADO = BLHSRVLIB . FN_SE_SEL_ERROR ( LPAD ( 97 , 4 , '0' ) ) ;

					END IF ;

				ELSE

					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - PROCSEGUIR N AGRUPAR ' );

					UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
						SET ESTADOPROCESO = 0 ,
							ESTADOFACTURA = ( CASE WHEN TIPOCANCELACION = 0	THEN 3
												WHEN TIPOCANCELACION = 2 THEN 7
												WHEN TIPOCANCELACION = 3 THEN 10
												WHEN TIPOCANCELACION = 4 THEN 11
											END )
						WHERE IDUNICOFACTURA = NUMIDUNICOFACTURA
						AND ESTADOFACTURA = 4 ;

				END IF ;

				--** Grabar en la tabla temporal del log 
				INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
				VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , NUMIDUNICOFACTURA , DECMONTODEBITOTEMP , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , VARMENSAJERESULTADO ) ;

				--** Guardar en la tabla temporal de notificaciones 
				INSERT INTO SESSION . PGCOLANOTIFICACIONESTMP ( FECHAINSERCION , CODTRANSACCION , ESTADO )
				VALUES ( CURRENT TIMESTAMP , NUMIDUNICOFACTURA , 0 ) ;

			END FOR FACT_LOOP ;

			CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LINEA ' || ' | NUMIDUNICOFACTURA: ' || NUMIDUNICOFACTURA || ' | IDUNICOFACTURA: ' || ' - ' || ' | CHRIDUNICOFACTURA: ' || CHRIDUNICOFACTURA );

			CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 1 ' );


			IF DECMONTODEBITO > 0 THEN

				CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 2 ' );

				IF NUMFORMAPAGO_ANT = 3 AND NUMTIPO <> 2 THEN

					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 3 ' );

					SET VARDESCRIPCIONDEBITO = SUBSTRING ( TRIM ( VARNOMBREBENEFICIARIO ) || ' ' || CAST ( INTCONTADORFACTOK AS VARCHAR ( 30 ) ) || ' FACTURAS' , 0 , 30 ) ;
							
					CALL BLHSRVLIB . SP_SE_SEL_NOMBRECIFPAGADOR ( NUMCIFPAGADOR , VARNOMBREPAGADOR , INTCODIGOERROR , VARMENSAJERESULTADO ) ;

					IF INTCODIGOERROR <> 0 OR TRIM ( VARNOMBREPAGADOR ) = '' THEN
						SET VARNOMBREPAGADOR = 'PAGANET' ;
					END IF ;

					SET VARDESCRIPCIONCREDITO = SUBSTRING ( TRIM ( VARNOMBREPAGADOR ) || ' ' || CAST ( INTCONTADORFACTOK AS VARCHAR ( 30 ) ) || ' FACTURAS' , 0 , 30 ) ;

					--SET VARMENSAJERESULTADO = 'CTA PAGADOR: ' || NUMCTAPAGADOR_ANT || ' - CTA BENEFICIARIO: ' || CHRCUENTABENEFICIARIO ;

					--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
					--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMENSAJERESULTADO ) ;

					--SET VARMENSAJERESULTADO = 'CIF PAGADOR: ' || NUMCIFPAGADOR || ' - CIF BENEFICIARIO: ' || NUMCIFBENEFICIARIO ;
							
					--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
					--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMENSAJERESULTADO ) ;	
					
					--PROCESO  STI PAGANET BENEFICIARIO INTERNACIONAL 
					SELECT IDUNICOFACTURA , MONTOCOMISION , MONTOIMPUESTO , TASASEGURIDAD , DESCRIPCIONCREDITO , CORREOSACK1 , CORREOSACK2 , DIRECCIONBENEF , CIUDADBENEF , NOMBREBANCO ,
					DIRECCIONBANCO , CIUDADBANCO , BENEFICIARIOTIPOBANCO , BENEFICIARIOBANCO , CIUDADBANCOINTERM , NOMBBANCOINTERM , DIRECBANCOINTERM , NUMCUENTABANCOINTERM , TIPOBANCOINTERM ,
					BANCOINTERM , GASTOSCUENTA , GASTOSBANCOCORRESPONSAL , GLTRANSACCION , GLCOMISION , GLGASTOSCORRESPONSAL , CLIENTID

					INTO CHRIDUNICOFACTURA , NUMMONTOCOMISION , NUMMONTOIMPUESTO , NUMTASASEGURIDAD , CHRDESCRIPCIONCREDITO , CHRCORREOSACK1 , CHRCORREOSACK2 , CHRDIRECCIONBENEF , CHRCIUDADBENEF , CHRNOMBREBANCO ,
					CHRDIRECCIONBANCO , CHRCIUDADBANCO , CHRBENEFICIARIOTIPOBANCO , CHRBENEFICIARIOBANCO , CHRCIUDADBANCOINTERM , CHRNOMBBANCOINTERM , CHRDIRECBANCOINTERM , CHRNUMCUENTABANCOINTERM , CHRTIPOBANCOINTERM ,
					CHRBANCOINTERM , CHRGASTOSCUENTA , NUMGASTOSBANCOCORRESPONSAL , CHRGLTRANSACCION , CHRGLCOMISION , CHRGLGASTOSCORRESPONSAL , NUMCLIENTID
					FROM BLHCYFILES . TB_SE_TRN_PGFACTURASEXTERIOR
					WHERE IDUNICOFACTURA = NUMIDUNICOFACTURA_ANT LIMIT 1 ;

					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR L1073 - CHRIDUNICOFACTURA: ' || NUMIDUNICOFACTURA || ' | NUMTASASEGURIDAD: ' || NUMTASASEGURIDAD || ' | CHRDESCRIPCIONCREDITO: ' || CHRDESCRIPCIONCREDITO || ' | CHRNOMBREBANCO: ' || CHRNOMBREBANCO || ' | CHRBENEFICIARIOTIPOBANCO: ' || CHRBENEFICIARIOTIPOBANCO || ' | CHRNUMCUENTABANCOINTERM: ' || CHRNUMCUENTABANCOINTERM || ' | CHRTIPOBANCOINTERM: ' || CHRTIPOBANCOINTERM || ' | CHRBANCOINTERM: ' || CHRBANCOINTERM || ' | CHRGLTRANSACCION: ' || CHRGLTRANSACCION || ' | CHRGLCOMISION: ' || CHRGLCOMISION || ' | CHRGLGASTOSCORRESPONSAL: ' || CHRGLGASTOSCORRESPONSAL || ' | NUMCLIENTID: ' || NUMCLIENTID );

					--MONEDA CUENTA PAGADOR 
					SET CHRMONEDACUENTAPAGADOR = ( SELECT ACMCCY FROM BLHCYFILES . ACMST WHERE ACMACC = NUMCTAPAGADOR_ANT FETCH FIRST 1 ROW ONLY ) ;
							
					--TELEFONO CUSPHN 
					SELECT CUSNA1 , CUSPHN , CASE WHEN CUSLGT = 2 THEN 'NAT' ELSE 'JSA' END AS LEGALTYPE INTO CHRNOMBREORDENANTE , DECTELEFONOPAGADOR , CHRTIPOCLIENTE FROM BLHCYFILES . CUMST WHERE CUSCUN = NUMCIFPAGADOR ;

					
					
					-- COMMISSIONTYPEID 
					-- 1 : PORCENTAJE 
					-- 2 : MONTO FIJO 
					--CONVERSION CODIGO MONEDA IC 
					IF CHRMONEDACUENTAPAGADOR = 'LPS' THEN
						SET CHRICMONEDACUENTAPAGADOR = 558 ;
					ELSEIF CHRMONEDACUENTAPAGADOR = 'USD' THEN
						SET CHRICMONEDACUENTAPAGADOR = 840 ;
					ELSEIF CHRMONEDACUENTAPAGADOR = 'EUR' THEN
						SET CHRICMONEDACUENTAPAGADOR = 978 ;
					END IF ;


					IF CHRMONEDACTABENEFICIARIO = 'LPS' THEN
						SET CHRICMONEDACUENTABENEFICIARIO = 558 ;
					ELSEIF CHRMONEDACTABENEFICIARIO = 'USD' THEN
						SET CHRICMONEDACUENTABENEFICIARIO = 840 ;
					ELSEIF CHRMONEDACTABENEFICIARIO = 'EUR' THEN
						SET CHRICMONEDACUENTABENEFICIARIO = 978 ;
					END IF ;
				
					--VALIDACION TIPO BANCO CORRESPONSAL 
					IF CHRTIPOBANCOINTERM = 'D' THEN
						SET INTCORRESPONDENTBANKTYPESID = 1 ;
					END IF ;

					IF CHRTIPOBANCOINTERM = 'A' THEN
						SET INTCORRESPONDENTBANKTYPESID = 2 ;
					END IF ;

					--CALCULOMONTO DEBITO - CREDITO COMISION 
					IF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_SITE_COMMISSIONS WHERE CLIENTID = NUMCLIENTID AND CURRENCYID = CHRICMONEDACUENTAPAGADOR
						AND SUBSIDIARYID = INTSUBSIDIARYID AND FEATUREID = INTFEATUREID ) > 0 THEN

							SET ( DECMONTODEBITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_SITE_COMMISSIONS WHERE CLIENTID = NUMCLIENTID
								AND CURRENCYID = CHRICMONEDACUENTAPAGADOR AND SUBSIDIARYID = INTSUBSIDIARYID AND FEATUREID = INTFEATUREID FETCH FIRST 1 ROW ONLY ) ;

							IF INTTIPOCOMISION = 1 THEN
								SET DECMONTODEBITOCOMISION = ( ( DECMONTODEBITOCOMISIONTEMP / 100 ) * DECMONTODEBITO ) ;
							ELSE
								SET DECMONTODEBITOCOMISION = DECMONTODEBITOCOMISIONTEMP ;
							END IF ;

							SET ( DECMONTOCREDITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_SITE_COMMISSIONS WHERE CLIENTID = NUMCLIENTID
								AND CURRENCYID = CHRICMONEDACUENTABENEFICIARIO AND SUBSIDIARYID = INTSUBSIDIARYID AND FEATUREID = INTFEATUREID FETCH FIRST 1 ROW ONLY ) ;

							IF INTTIPOCOMISION = 1 THEN
								SET DECMONTOCREDITOCOMISION = ( ( DECMONTOCREDITOCOMISIONTEMP / 100 ) * DECMONTOCREDITO ) ;
							ELSE
								SET DECMONTOCREDITOCOMISION = DECMONTOCREDITOCOMISIONTEMP ;
							END IF ;
								
					
					ELSEIF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_GLOBAL_COMMISSIONS WHERE SUBSIDIARYID = INTSUBSIDIARYID AND CURRENCYID = CHRICMONEDACUENTAPAGADOR AND FEATUREID = INTFEATUREID ) > 0 THEN
							
							SET ( DECMONTODEBITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_GLOBAL_COMMISSIONS
								WHERE SUBSIDIARYID = INTSUBSIDIARYID AND CURRENCYID = CHRICMONEDACUENTAPAGADOR AND FEATUREID = INTFEATUREID AND COMMISSIONVALUE > 0 FETCH FIRST 1 ROW ONLY ) ;
							
							IF INTTIPOCOMISION = 1 THEN
								SET DECMONTODEBITOCOMISION = ( DECMONTODEBITOCOMISIONTEMP * DECMONTODEBITO ) ;
							ELSE
								SET DECMONTODEBITOCOMISION = DECMONTODEBITOCOMISIONTEMP ;
							END IF ;

							SET ( DECMONTOCREDITOCOMISIONTEMP , INTTIPOCOMISION , NUMMINVALUE , NUMMAXVALUE ) = ( SELECT COMMISSIONVALUE , COMMISSIONTYPEID , MINVALUE , MAXVALUE FROM BLHCYFILES . TB_SE_TRN_GLOBAL_COMMISSIONS
								WHERE SUBSIDIARYID = INTSUBSIDIARYID AND CURRENCYID = CHRICMONEDACUENTABENEFICIARIO AND FEATUREID = INTFEATUREID AND COMMISSIONVALUE > 0 FETCH FIRST 1 ROW ONLY ) ;
							
							IF INTTIPOCOMISION = 1 THEN
								SET DECMONTOCREDITOCOMISION = ( DECMONTOCREDITOCOMISIONTEMP * DECMONTOCREDITO ) ;

							ELSE
								SET DECMONTOCREDITOCOMISION = DECMONTOCREDITOCOMISIONTEMP ;
							END IF ;
					END IF ;

					IF INTTIPOCOMISION = 1 THEN
						IF DECMONTODEBITOCOMISION < NUMMINVALUE THEN
							SET DECMONTODEBITOCOMISION = NUMMINVALUE ;
						ELSEIF DECMONTODEBITOCOMISION > NUMMAXVALUE THEN
							SET DECMONTODEBITOCOMISION = NUMMAXVALUE ;
						END IF ;

						IF DECMONTOCREDITOCOMISION < NUMMINVALUE THEN
							SET DECMONTOCREDITOCOMISION = NUMMINVALUE ;
						ELSEIF DECMONTOCREDITOCOMISION > NUMMAXVALUE THEN
							SET DECMONTOCREDITOCOMISION = NUMMAXVALUE ;
						END IF ;
					END IF ;

					--CALCULO MONTO DEBITO - CREDITO GASTO CORRESPONSAL 
					IF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_SITECORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR
						AND SUBSIDIARYID = INTSUBSIDIARYID AND CLIENTID = NUMCLIENTID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID ) > 0 THEN

							SET DECMONTODEBITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_SITECORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR
							AND SUBSIDIARYID = INTSUBSIDIARYID AND CLIENTID = NUMCLIENTID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;

							SET DECMONTOCREDITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_SITECORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTABENEFICIARIO
							AND SUBSIDIARYID = INTSUBSIDIARYID AND CLIENTID = NUMCLIENTID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;

					ELSEIF ( SELECT COUNT ( * ) FROM BLHCYFILES . TB_SE_TRN_GLOBALCORRESPONDENTBANKEXPENSES WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR
						AND SUBSIDIARYID = INTSUBSIDIARYID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID ) > 0 THEN

							SET DECMONTODEBITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_GLOBALCORRESPONDENTBANKEXPENSES
								WHERE CURRENCYID = CHRICMONEDACUENTAPAGADOR AND SUBSIDIARYID = INTSUBSIDIARYID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;

							SET DECMONTOCREDITOGASTOCORRESPONSAL = ( SELECT CHARGEAMOUNT FROM BLHCYFILES . TB_SE_TRN_GLOBALCORRESPONDENTBANKEXPENSES
								WHERE CURRENCYID = CHRICMONEDACUENTABENEFICIARIO AND SUBSIDIARYID = INTSUBSIDIARYID AND CORRESPONDENTBANKTYPESID = INTCORRESPONDENTBANKTYPESID FETCH FIRST 1 ROW ONLY ) ;
					END IF ;

					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 4 ' );


					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - Parametros SP_SE_VAR_TRANSFERENCIAEXTERIOR2 - CHRIDUNICOFACTURA: ' || NUMIDUNICOFACTURA || ' | NUMCIFPAGADOR: ' || NUMCIFPAGADOR || ' | NUMCTAPAGADOR_ANT: ' || NUMCTAPAGADOR_ANT || ' | CHRGLTRANSACCION: ' || CHRGLTRANSACCION || ' | CHRMONEDACUENTAPAGADOR: ' || CHRMONEDACUENTAPAGADOR || ' | CHRCUENTABENEFICIARIO: ' || CHRCUENTABENEFICIARIO || ' | CHRMONEDACTABENEFICIARIO: ' || CHRMONEDACTABENEFICIARIO || ' | DECMONTODEBITO: ' || DECMONTODEBITO || ' | CHRDESCRIPCIONCREDITO: ' || CHRDESCRIPCIONCREDITO || ' | CHRBANCOINTERM: ' || CHRBANCOINTERM || ' | CHRNUMCUENTABANCOINTERM: ' || CHRNUMCUENTABANCOINTERM );					
			
					CALL BLHSRVLIB . SP_SE_VAR_TRANSFERENCIAEXTERIOR ( NUMCIFPAGADOR , NUMIDUNICOFACTURA_ANT , NUMCTAPAGADOR_ANT , CHRGLTRANSACCION , CHRMONEDACUENTAPAGADOR ,
					CHRCUENTABENEFICIARIO , CHRMONEDACTABENEFICIARIO , VARNOMBREBENEFICIARIO , CHRDIRECCIONBENEF , CHRCIUDADBENEF ,
					CHRBENEFICIARIOTIPOBANCO , CHRBENEFICIARIOBANCO , CHRNOMBREBANCO , CHRDIRECCIONBANCO , CHRCIUDADBANCO ,
					DECMONTODEBITO , DECMONTODEBITO , CHRDESCRIPCIONCREDITO , CHRGASTOSCUENTA , CHRNOMBREORDENANTE , CHRDOCUMENTOIDENTIDADBENEFICIARIO , DECTELEFONOPAGADOR , CHRCORREOSACK1 ,
					CHRCORREOSACK2 , DECTCUSDCOMPRA , DECTCUSDVENTA , NUMGASTOSBANCOCORRESPONSAL , NUMMONTOCOMISION , NUMTASASEGURIDAD , CHRTIPOBANCOINTERM ,
					CHRBANCOINTERM , CHRNOMBBANCOINTERM , CHRDIRECBANCOINTERM , CHRCIUDADBANCOINTERM , CHRCIUDADBANCOINTERM ,
					CHRNUMCUENTABANCOINTERM , VARNUMEROREFERENCIA , INTTIPORESULTADO , VARMENSAJERESULTADO ) ;
					
					CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - Resultado SP_SE_VAR_TRANSFERENCIAEXTERIOR1 - CHRIDUNICOFACTURA: ' || NUMIDUNICOFACTURA || ' | INTTIPORESULTADO: ' || INTTIPORESULTADO || ' | VARMENSAJERESULTADO: ' || VARMENSAJERESULTADO );


					IF INTTIPORESULTADO <> 0 THEN
						SET INTTIPORESULTADO = INTTIPORESULTADO ;
						SET VARMENSAJERESULTADO = VARMENSAJERESULTADO ;
						SIGNAL SQLSTATE '75000' ;
					END IF ;

					-------------------------- 
					--MOVIMIENTOS TRANSACCION-- 
					--------------------------- 
					------------------- 
					--DEBITO COMISION-- 
					------------------- 
				
					----------------------------- 
					--DEBITO GASTO CORRESPONSAL-- 
					----------------------------- 
			
					--** Se guarda el mensaje original para poder marcar los registros de facturas en el log en caso de que no se aplique el movimiento final. 
					SET VARMENSAJE = VARMENSAJERESULTADO ;

					--SET VARMENSAJERESULTADO = 'RESULTADO LLAMADO PROCESO PAGO FACTURAS: ' || VARMENSAJERESULTADO || 'Numero Referencia: ' || VARNUMEROREFERENCIA ;						
							
					--INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
					--VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , DECMONTODEBITO , NUMSALDODISPONIBLECUENTA , NUMTASADECOMPRA , NUMTASADEVENTA , VARMENSAJERESULTADO ) ;

					IF INTTIPORESULTADO = 0 THEN
							
						IF VARCELULARBENEFICIARIO <> '' THEN

							SET VARMENSAJESMS = LEFT ( 'Pag@Net: ' || TRIM ( VARNOMBREPAGADOR ) || ' le ha CANCELADO el pago de factura(s) por un monto de ' || CHRMONEDAFACTURA_ANT || ' ' || DECMONTOCREDITO || ' . Para mayor información ingrese a Banc@Net. Gracias.' , 160 ) ;
								
							--** Enviar Notificacion SMS						 
							CALL BLHSRVLIB . SP_SE_INS_SMS ( VARCELULARBENEFICIARIO , VARMENSAJESMS , 'PG' , 2 , 'PG' , '' , 0 , 3 , INTCODERRORSMS , VARMSJERRORSMS ) ;

							/*
							IF INTCODERRORSMS = 0 THEN
								SET VARMSJERRORSMS = 'SMS OK' ;
							ELSE
								SET VARMSJERRORSMS = LEFT ( 'SMS ERROR: ' || TRIM ( VARMSJERRORSMS ) , 1000 ) ;
							END IF ;

							INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
							VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMSJERRORSMS ) ;
							*/
						ELSE
							
							SET VARMSJERRORSMS = 'SIN  CELULAR' ;

							INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
							VALUES ( CURRENT TIMESTAMP , NUMNUMEROSEGURIDAD , 0 , 0 , 0 , 0 , 0 , VARMSJERRORSMS ) ;

						END IF ;

							--** Se guarda en la tabla final del log los datos 
						INSERT INTO BLHCYFILES . TB_SE_TRN_PGLOGPROCESO
						SELECT * FROM SESSION . PGLOGPROCESOTMP ;
								
							--** Se guarda en la tabla final de notificaciones los datos 
						INSERT INTO BLHCYFILES . TB_SE_TRN_PGNOTIFICACIONES
						SELECT * FROM SESSION . PGCOLANOTIFICACIONESTMP ;
		
						COMMIT ;
								
							--** Se borran los registros guardados en las tablas temporales. 
						DELETE FROM SESSION . PGLOGPROCESOTMP ;
						DELETE FROM SESSION . PGCOLANOTIFICACIONESTMP ;
								
					ELSE
							
						ROLLBACK HOLD ;
								
							--** Se actualiza los registros de la tabla PGLOGPROCESOTMP para que la transacción quede con el error actualizado 
						UPDATE SESSION . PGLOGPROCESOTMP SET MENSAJEPROCESO = VARMENSAJE
						WHERE NUMEROGRUPO = NUMNUMEROSEGURIDAD
						AND CODTRANSACCION <> 0
						AND MENSAJEPROCESO = 'APLICADA' ;
								
							--** Se guarda en la tabla final del log los datos 
						INSERT INTO BLHCYFILES . TB_SE_TRN_PGLOGPROCESO
						SELECT * FROM SESSION . PGLOGPROCESOTMP ;
								
							--** Se guarda en la tabla final de notificaciones los datos 
						INSERT INTO BLHCYFILES . TB_SE_TRN_PGNOTIFICACIONES
						SELECT * FROM SESSION . PGCOLANOTIFICACIONESTMP ;
								
						COMMIT ;
								
							--** Se borran los registros guardados en las tablas temporales. 
						DELETE FROM SESSION . PGLOGPROCESOTMP ;
						DELETE FROM SESSION . PGCOLANOTIFICACIONESTMP ;
								
					END IF ;

				END IF ;

			ELSE
				
				CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 5 ' );

				--IF IntTipoResultado = - 1 THEN 
					--SET VarMensajeResultado = VarMensaje ; 
				--END IF ; 
				-- ** Se guarda registro en el LOG 
				INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
				VALUES ( CURRENT TIMESTAMP , INTTIPORESULTADO , 0 , 0 , 0 , 0 , 0 , VARMENSAJERESULTADO ) ;

			END IF ;

		ELSE

			CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 5.1 ' );
			
			--IF IntTipoResultado = - 1 THEN 
				--SET VarMensajeResultado = VarMensaje ; 
			--END IF ; 
			-- ** Se guarda registro en el LOG 
			INSERT INTO SESSION . PGLOGPROCESOTMP ( FECHAINSERCION , NUMEROGRUPO , CODTRANSACCION , MONTODEBITARCTA , SALDOCTADEBITAR , TCCOMPRA , TCVENTA , MENSAJEPROCESO )
			VALUES ( CURRENT TIMESTAMP , INTTIPORESULTADO , 0 , 0 , 0 , 0 , 0 , VARMENSAJERESULTADO ) ;

		END IF ;

		CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 6 ' );
		
		UPDATE BLHCYFILES . TB_SE_TRN_PGTRANSACCIONESFACTURAS
		SET ESTADOPROCESO = 0 ,
			ESTADOFACTURA = ( CASE WHEN TIPOCANCELACION = 0 THEN 3
								WHEN TIPOCANCELACION = 2 THEN 7
								WHEN TIPOCANCELACION = 3 THEN 10
								WHEN TIPOCANCELACION = 4 THEN 11
							END )
		WHERE ESTADOFACTURA = 4
		AND ESTADOPROCESO = INTESTADOPROCESO ;

		CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 7 ' );

		--** Se guarda en la tabla final del log los datos 
		--INSERT INTO BLHCYFILES . TB_SE_TRN_PGLOGPROCESO
		--SELECT * FROM SESSION . PGLOGPROCESOTMP ;

		CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 8 ' );


		--** Se guarda en la tabla final de notificaciones los datos 
		INSERT INTO BLHCYFILES . TB_SE_TRN_PGNOTIFICACIONES
		SELECT * FROM SESSION . PGCOLANOTIFICACIONESTMP ;

		CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 9 ' );
		
		--** Se borran los registros guardados en las tablas temporales. 
		DELETE FROM SESSION . PGLOGPROCESOTMP ;
		DELETE FROM SESSION . PGCOLANOTIFICACIONESTMP ;

		CALL BLHSRVLIB . SP_SE_INS_PGLOGPROCESO ( NUMIDUNICOFACTURA , 0 , 0 , 0 , 0 , 0 , 'SP_SE_VAR_PROCESARPAGOS_EXTERIOR - LLEGA 10 ' );
		
		--** Se llama al proceso que envia los correos. 
		CALL BLHSRVLIB . SP_SE_VAR_ENVIARCORREOSPAGANET ( ) ;
		
		--** Se aplican los cambios. 
		COMMIT ;		

	END P1
